language: java
install: true
addons:
  ssh_known_hosts: 139.59.61.26
after_success:
- chmod +x _scripts/deploy.sh
- _scripts/deploy.sh
before_install:
- openssl aes-256-cbc -K $encrypted_65abf4490a15_key -iv $encrypted_65abf4490a15_iv
  -in travis.enc -out travis -d
